INSERT INTO provider_model_capability_presets(
  preset_key, display_name, modality, match_patterns, task_types,
  input_limits, output_limits, quality_tiers, provider_options_schema, pricing_policy, priority, enabled
) VALUES
(
  'deepseek/deepseek-v4-flash',
  'DeepSeek: DeepSeek V4 Flash',
  'text',
  '["deepseek/deepseek-v4-flash","deepseek/deepseek-v4-flash-20260423","deepseek-v4-flash"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":false,"supportsMultimodalInput":false,"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":1,"view":"week","metric":"total_tokens","date":"2026-07-04","value":5351595576914}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'xiaomi/mimo-v2.5',
  'Xiaomi: MiMo-V2.5',
  'multimodal',
  '["xiaomi/mimo-v2.5","xiaomi/mimo-v2.5-20260422","mimo-v2.5"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text","image","audio","video"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":false,"supportsMultimodalInput":true,"supportedInputTypes":["text","image","audio","video"],"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":2,"view":"week","metric":"total_tokens","date":"2026-07-04","value":4302811425246}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'minimax/minimax-m3',
  'MiniMax: MiniMax M3',
  'multimodal',
  '["minimax/minimax-m3","minimax/minimax-m3-20260531","minimax-m3"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text","image","video"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":false,"supportsMultimodalInput":true,"supportedInputTypes":["text","image","video"],"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":3,"view":"week","metric":"total_tokens","date":"2026-07-04","value":4021464732196}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'tencent/hy3-preview',
  'Tencent: Hy3 preview',
  'text',
  '["tencent/hy3-preview","tencent/hy3-preview-20260421","hy3-preview"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":false,"supportsMultimodalInput":false,"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":4,"view":"week","metric":"total_tokens","date":"2026-07-04","value":3374445656632}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'z-ai/glm-5.2',
  'Z.ai: GLM 5.2',
  'text',
  '["z-ai/glm-5.2","z-ai/glm-5.2-20260616","glm-5.2"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":true,"reasoningLevels":["low","medium","high"],"supportsMultimodalInput":false,"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":5,"view":"week","metric":"total_tokens","date":"2026-07-04","value":2537516752031}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'deepseek/deepseek-v4-pro',
  'DeepSeek: DeepSeek V4 Pro',
  'text',
  '["deepseek/deepseek-v4-pro","deepseek/deepseek-v4-pro-20260423","deepseek-v4-pro"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":false,"supportsMultimodalInput":false,"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":6,"view":"week","metric":"total_tokens","date":"2026-07-04","value":2247637407107}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'anthropic/claude-opus-4.8',
  'Anthropic: Claude Opus 4.8',
  'multimodal',
  '["anthropic/claude-opus-4.8","anthropic/claude-4.8-opus-20260528","claude-opus-4.8","claude-4.8-opus"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text","image","file"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":true,"reasoningLevels":["low","medium","high","max"],"supportsMultimodalInput":true,"supportedInputTypes":["text","image","file"],"requestModes":["messages","chat_completions"],"openrouterRanking":{"category":"text","rank":7,"view":"week","metric":"total_tokens","date":"2026-07-04","value":2084583459013}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'anthropic/claude-opus-4.7',
  'Anthropic: Claude Opus 4.7',
  'multimodal',
  '["anthropic/claude-opus-4.7","anthropic/claude-4.7-opus-20260416","claude-opus-4.7","claude-4.7-opus"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text","image","file"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":true,"reasoningLevels":["low","medium","high","max"],"supportsMultimodalInput":true,"supportedInputTypes":["text","image","file"],"requestModes":["messages","chat_completions"],"openrouterRanking":{"category":"text","rank":8,"view":"week","metric":"total_tokens","date":"2026-07-04","value":2020514507849}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'stepfun/step-3.7-flash',
  'StepFun: Step 3.7 Flash',
  'multimodal',
  '["stepfun/step-3.7-flash","stepfun/step-3.7-flash-20260528","step-3.7-flash"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text","image","video"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":false,"supportsMultimodalInput":true,"supportedInputTypes":["text","image","video"],"requestModes":["chat_completions"],"openrouterRanking":{"category":"text","rank":9,"view":"week","metric":"total_tokens","date":"2026-07-04","value":1557831978023}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'anthropic/claude-sonnet-4.6',
  'Anthropic: Claude Sonnet 4.6',
  'multimodal',
  '["anthropic/claude-sonnet-4.6","anthropic/claude-4.6-sonnet-20260217","claude-sonnet-4.6","claude-4.6-sonnet"]'::jsonb,
  '["text.generate","text.stream"]'::jsonb,
  '{"inputTypes":["text","image","file"]}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  '{"xCapabilities":{"supportsAsyncTask":false,"supportsStreaming":true,"supportsReasoning":true,"supportsReasoningLevels":true,"reasoningLevels":["low","medium","high"],"supportsMultimodalInput":true,"supportedInputTypes":["text","image","file"],"requestModes":["messages","chat_completions"],"openrouterRanking":{"category":"text","rank":10,"view":"week","metric":"total_tokens","date":"2026-07-04","value":1465196371905}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/gemini-2.5-flash-image',
  'Google: Nano Banana (Gemini 2.5 Flash Image)',
  'image',
  '["google/gemini-2.5-flash-image","gemini-2.5-flash-image"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["standard"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":3,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedAspectRatios":["1:1","2:3","3:2","3:4","4:3","4:5","5:4","9:16","16:9","21:9"],"openrouterRanking":{"category":"image","rank":1,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":2039727}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/gemini-3.1-flash-image-preview',
  'Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)',
  'image',
  '["google/gemini-3.1-flash-image-preview","google/gemini-3.1-flash-image-preview-20260226","gemini-3.1-flash-image-preview"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["512","1K","2K","4K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":14,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedResolutions":["512","1K","2K","4K"],"supportedAspectRatios":["1:1","1:4","1:8","2:3","3:2","3:4","4:1","4:3","4:5","5:4","8:1","9:16","16:9","21:9"],"openrouterRanking":{"category":"image","rank":2,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":865381}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/gemini-3.1-flash-image',
  'Google: Nano Banana 2 (Gemini 3.1 Flash Image)',
  'image',
  '["google/gemini-3.1-flash-image","google/gemini-3.1-flash-image-20260528","gemini-3.1-flash-image"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["512","1K","2K","4K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":14,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedResolutions":["512","1K","2K","4K"],"supportedAspectRatios":["1:1","1:4","1:8","2:3","3:2","3:4","4:1","4:3","4:5","5:4","8:1","9:16","16:9","21:9"],"openrouterRanking":{"category":"image","rank":3,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":650709}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/gemini-3-pro-image-preview',
  'Google: Nano Banana Pro (Gemini 3 Pro Image Preview)',
  'image',
  '["google/gemini-3-pro-image-preview","google/gemini-3-pro-image-preview-20251120","gemini-3-pro-image-preview"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["1K","2K","4K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":14,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedResolutions":["1K","2K","4K"],"supportedAspectRatios":["1:1","2:3","3:2","3:4","4:3","4:5","5:4","9:16","16:9","21:9"],"openrouterRanking":{"category":"image","rank":4,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":500886}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'x-ai/grok-imagine-image-quality',
  'xAI: Grok Imagine Image Quality',
  'image',
  '["x-ai/grok-imagine-image-quality","x-ai/grok-imagine-image-quality-20260512","grok-imagine-image-quality"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["1K","2K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":3,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedResolutions":["1K","2K"],"supportedAspectRatios":["1:1","3:4","4:3","9:16","16:9","2:3","3:2","9:19.5","19.5:9","9:20","20:9","1:2","2:1","auto"],"openrouterRanking":{"category":"image","rank":5,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":383390}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/gemini-3-pro-image',
  'Google: Nano Banana Pro (Gemini 3 Pro Image)',
  'image',
  '["google/gemini-3-pro-image","google/gemini-3-pro-image-20260528","gemini-3-pro-image"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["1K","2K","4K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":14,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedResolutions":["1K","2K","4K"],"supportedAspectRatios":["1:1","2:3","3:2","3:4","4:3","4:5","5:4","9:16","16:9","21:9"],"openrouterRanking":{"category":"image","rank":6,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":328921}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'bytedance-seed/seedream-4.5',
  'ByteDance Seed: Seedream 4.5',
  'image',
  '["bytedance-seed/seedream-4.5","bytedance-seed/seedream-4.5-20251203","seedream-4.5"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["1K","2K","4K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":14,"supportsStreaming":false,"supportsSeed":true,"requestModes":["images.generate","images.edit"],"supportedResolutions":["1K","2K","4K"],"supportedAspectRatios":["1:1","1:2","2:1","2:3","3:2","3:4","4:3","4:5","5:4","9:16","16:9","9:19.5","19.5:9","9:20","20:9","9:21","21:9","auto"],"openrouterRanking":{"category":"image","rank":7,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":133224}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'openai/gpt-5.4-image-2',
  'OpenAI: GPT-5.4 Image 2',
  'image',
  '["openai/gpt-5.4-image-2","openai/gpt-5.4-image-2-20260421","gpt-5.4-image-2"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image","file"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["low","medium","high"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":16,"supportsStreaming":true,"requestModes":["images.generate","images.edit"],"quality":["auto","low","medium","high"],"background":["auto","opaque"],"outputCompression":{"min":0,"max":100},"openrouterRanking":{"category":"image","rank":8,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":130009}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/gemini-3.1-flash-lite-image',
  'Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)',
  'image',
  '["google/gemini-3.1-flash-lite-image","google/gemini-3.1-flash-lite-image-20260630","gemini-3.1-flash-lite-image"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"]}'::jsonb,
  '["1K"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":14,"supportsStreaming":false,"requestModes":["images.generate","images.edit"],"supportedResolutions":["1K"],"supportedAspectRatios":["1:1","1:4","1:8","2:3","3:2","3:4","4:1","4:3","4:5","5:4","8:1","9:16","16:9","21:9"],"openrouterRanking":{"category":"image","rank":9,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":112377}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'black-forest-labs/flux.2-klein-4b',
  'Black Forest Labs: FLUX.2 Klein 4B',
  'image',
  '["black-forest-labs/flux.2-klein-4b","flux.2-klein-4b"]'::jsonb,
  '["image.generate"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"responseFormats":["url","b64_json"],"outputFormats":["png","jpeg"]}'::jsonb,
  '["standard"]'::jsonb,
  '{"imageEndpointKey":"image_generate","xCapabilities":{"supportsAsyncTask":false,"supportsReferences":true,"supportsReferenceImages":true,"maxReferenceImages":4,"supportsStreaming":false,"supportsSeed":true,"requestModes":["images.generate","images.edit"],"outputFormats":["png","jpeg"],"openrouterRanking":{"category":"image","rank":10,"view":"week","metric":"image_output_requests","date":"2026-07-04","value":91867}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/veo-3.1-fast',
  'Google: Veo 3.1 Fast',
  'video',
  '["google/veo-3.1-fast","google/veo-3.1-fast-20260320","veo-3.1-fast"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["720p","1080p","4K"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[4,6,8],"resolutions":["720p","1080p","4K"],"supportsSeed":true,"generateAudio":true,"allowedPassthroughParameters":["personGeneration","aspectRatio","negativePrompt","conditioningScale","enhancePrompt"],"openrouterRanking":{"category":"video","rank":1,"view":"week","metric":"count","date":"2026-07-04","value":42946}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/veo-3.1',
  'Google: Veo 3.1',
  'video',
  '["google/veo-3.1","google/veo-3.1-20260320","veo-3.1"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["720p","1080p","4K"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[4,6,8],"resolutions":["720p","1080p","4K"],"supportsSeed":true,"generateAudio":true,"allowedPassthroughParameters":["personGeneration","aspectRatio","negativePrompt","conditioningScale","enhancePrompt"],"openrouterRanking":{"category":"video","rank":2,"view":"week","metric":"count","date":"2026-07-04","value":25132}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'bytedance/seedance-2.0',
  'ByteDance: Seedance 2.0',
  'video',
  '["bytedance/seedance-2.0","bytedance/seedance-2.0-20260414","seedance-2.0"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["480p","720p","1080p","4K"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[4,5,6,7,8,9,10,11,12,13,14,15],"resolutions":["480p","720p","1080p","4K"],"supportsSeed":true,"generateAudio":true,"allowedPassthroughParameters":["watermark","req_key"],"openrouterRanking":{"category":"video","rank":3,"view":"week","metric":"count","date":"2026-07-04","value":17125}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'google/veo-3.1-lite',
  'Google: Veo 3.1 Lite',
  'video',
  '["google/veo-3.1-lite","google/veo-3.1-lite-20260331","veo-3.1-lite"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["720p","1080p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[4,6,8],"resolutions":["720p","1080p"],"supportsSeed":true,"generateAudio":true,"allowedPassthroughParameters":["personGeneration","aspectRatio","negativePrompt","conditioningScale","enhancePrompt"],"openrouterRanking":{"category":"video","rank":4,"view":"week","metric":"count","date":"2026-07-04","value":15349}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'x-ai/grok-imagine-video',
  'xAI: Grok Imagine Video',
  'video',
  '["x-ai/grok-imagine-video","x-ai/grok-imagine-video-20260512","grok-imagine-video"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["480p","720p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":false,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame"],"durations":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],"resolutions":["480p","720p"],"supportsSeed":false,"generateAudio":null,"openrouterRanking":{"category":"video","rank":5,"view":"week","metric":"count","date":"2026-07-04","value":9511}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'bytedance/seedance-2.0-fast',
  'ByteDance: Seedance 2.0 Fast',
  'video',
  '["bytedance/seedance-2.0-fast","bytedance/seedance-2.0-fast-20260414","seedance-2.0-fast"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["480p","720p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[4,5,6,7,8,9,10,11,12,13,14,15],"resolutions":["480p","720p"],"supportsSeed":true,"generateAudio":true,"allowedPassthroughParameters":["watermark","req_key"],"openrouterRanking":{"category":"video","rank":6,"view":"week","metric":"count","date":"2026-07-04","value":7266}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'bytedance/seedance-1-5-pro',
  'ByteDance: Seedance 1.5 Pro',
  'video',
  '["bytedance/seedance-1-5-pro","bytedance/seedance-1-5-pro-20260320","seedance-1-5-pro"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["480p","720p","1080p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[4,5,6,7,8,9,10,11,12],"resolutions":["480p","720p","1080p"],"supportsSeed":true,"generateAudio":true,"allowedPassthroughParameters":["watermark","req_key"],"openrouterRanking":{"category":"video","rank":7,"view":"week","metric":"count","date":"2026-07-04","value":3724}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'kwaivgi/kling-v3.0-pro',
  'Kling: Video v3.0 Pro',
  'video',
  '["kwaivgi/kling-v3.0-pro","kwaivgi/kling-v3.0-pro-20260429","kling-v3.0-pro"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["720p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[3,4,5,6,7,8,9,10,11,12,13,14,15],"resolutions":["720p"],"supportsSeed":false,"generateAudio":true,"allowedPassthroughParameters":["negative_prompt","cfg_scale"],"openrouterRanking":{"category":"video","rank":8,"view":"week","metric":"count","date":"2026-07-04","value":3425}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'kwaivgi/kling-v3.0-std',
  'Kling: Video v3.0 Standard',
  'video',
  '["kwaivgi/kling-v3.0-std","kwaivgi/kling-v3.0-std-20260429","kling-v3.0-std"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["720p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame","last_frame"],"durations":[3,4,5,6,7,8,9,10,11,12,13,14,15],"resolutions":["720p"],"supportsSeed":false,"generateAudio":true,"allowedPassthroughParameters":["negative_prompt","cfg_scale"],"openrouterRanking":{"category":"video","rank":9,"view":"week","metric":"count","date":"2026-07-04","value":3202}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
),
(
  'alibaba/happyhorse-1.1',
  'Alibaba: HappyHorse 1.1',
  'video',
  '["alibaba/happyhorse-1.1","alibaba/happyhorse-1.1-20260624","happyhorse-1.1"]'::jsonb,
  '["video.text_to_video","video.image_to_video","video.create_task","video.poll_task","video.cancel_task"]'::jsonb,
  '{"inputTypes":["text","image"]}'::jsonb,
  '{"outputTypes":["video"]}'::jsonb,
  '["720p","1080p"]'::jsonb,
  '{"videoCreateEndpointKey":"video_create","videoPollEndpointKey":"video_poll","videoCancelEndpointKey":"video_cancel","xCapabilities":{"supportsAsyncTask":true,"supportsReferenceImages":true,"supportsFirstFrame":true,"supportsLastFrame":false,"supportsVideoReference":false,"requestModes":["async_create","poll","cancel"],"referenceTypes":["image","first_frame"],"durations":[3,4,5,6,7,8,9,10,11,12,13,14,15],"resolutions":["720p","1080p"],"supportsSeed":true,"generateAudio":null,"openrouterRanking":{"category":"video","rank":10,"view":"week","metric":"count","date":"2026-07-04","value":2488}}}'::jsonb,
  '{"currency":"USD"}'::jsonb,
  5,
  true
)
ON CONFLICT (preset_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  modality = EXCLUDED.modality,
  match_patterns = EXCLUDED.match_patterns,
  task_types = EXCLUDED.task_types,
  input_limits = EXCLUDED.input_limits,
  output_limits = EXCLUDED.output_limits,
  quality_tiers = EXCLUDED.quality_tiers,
  provider_options_schema = EXCLUDED.provider_options_schema,
  pricing_policy = EXCLUDED.pricing_policy,
  priority = EXCLUDED.priority,
  enabled = EXCLUDED.enabled;

INSERT INTO schema_migrations(version) VALUES ('000027_openrouter_ranked_model_presets')
ON CONFLICT (version) DO NOTHING;
