package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

var (
	eventNamePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+$`)
	sqlEventPattern  = regexp.MustCompile(`'([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+)'`)
)

type catalogFile struct {
	Version int               `yaml:"version"`
	Events  []eventDefinition `yaml:"events"`
}

type eventDefinition struct {
	Name                  string   `yaml:"name"`
	SchemaVersion         int      `yaml:"schemaVersion"`
	ScopeType             string   `yaml:"scopeType"`
	AggregateType         string   `yaml:"aggregateType"`
	RequiredPayloadFields []string `yaml:"requiredPayloadFields"`
	Terminal              bool     `yaml:"terminal"`
	DeprecatedAt          string   `yaml:"deprecatedAt,omitempty"`
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "verify generated files without writing")
	discover := flag.Bool("discover", false, "print statically discoverable backend event names")
	flag.Parse()
	absRoot, err := filepath.Abs(*root)
	fatalIf(err)
	if *discover {
		names, err := discoverEventNames(absRoot)
		fatalIf(err)
		for _, name := range names {
			fmt.Println(name)
		}
		return
	}
	catalog, err := loadCatalog(filepath.Join(absRoot, "packages", "events", "catalog.yaml"))
	fatalIf(err)
	outputs, err := renderOutputs(catalog)
	fatalIf(err)
	for relativePath, content := range outputs {
		path := filepath.Join(absRoot, filepath.FromSlash(relativePath))
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil {
				fatalIf(fmt.Errorf("read %s: %w", relativePath, err))
			}
			if !bytes.Equal(existing, content) {
				fatalIf(fmt.Errorf("%s is stale; run go run ./cmd/events-gen", relativePath))
			}
			continue
		}
		fatalIf(os.MkdirAll(filepath.Dir(path), 0o755))
		fatalIf(os.WriteFile(path, content, 0o644))
	}
}

func loadCatalog(path string) (catalogFile, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return catalogFile{}, err
	}
	var catalog catalogFile
	if err := yaml.Unmarshal(raw, &catalog); err != nil {
		return catalogFile{}, err
	}
	if catalog.Version <= 0 || len(catalog.Events) == 0 {
		return catalogFile{}, errors.New("event catalog requires a positive version and at least one event")
	}
	seen := map[string]bool{}
	for index := range catalog.Events {
		event := &catalog.Events[index]
		if !eventNamePattern.MatchString(event.Name) {
			return catalogFile{}, fmt.Errorf("invalid event name %q", event.Name)
		}
		if seen[event.Name] {
			return catalogFile{}, fmt.Errorf("duplicate event name %q", event.Name)
		}
		seen[event.Name] = true
		if event.SchemaVersion <= 0 || event.ScopeType == "" || event.AggregateType == "" {
			return catalogFile{}, fmt.Errorf("event %s has incomplete contract metadata", event.Name)
		}
		sort.Strings(event.RequiredPayloadFields)
	}
	sort.Slice(catalog.Events, func(i, j int) bool { return catalog.Events[i].Name < catalog.Events[j].Name })
	return catalog, nil
}

func renderOutputs(catalog catalogFile) (map[string][]byte, error) {
	functions := template.FuncMap{"quote": strconv.Quote}
	goTemplate := template.Must(template.New("go").Funcs(functions).Parse(`// Code generated by cmd/events-gen; DO NOT EDIT.
package events

var CatalogVersion = {{.Version}}

var Catalog = map[string]Definition{
{{- range .Events}}
	{{quote .Name}}: {Name: {{quote .Name}}, SchemaVersion: {{.SchemaVersion}}, ScopeType: {{quote .ScopeType}}, AggregateType: {{quote .AggregateType}}, RequiredPayloadFields: []string{ {{- range .RequiredPayloadFields}}{{quote .}},{{end}} }, Terminal: {{.Terminal}}, DeprecatedAt: {{quote .DeprecatedAt}}},
{{- end}}
}
`))
	tsTemplate := template.Must(template.New("ts").Funcs(functions).Parse(`// Code generated by cmd/events-gen; DO NOT EDIT.
export const projectEventNames = [
{{- range .Events}}
  {{quote .Name}},
{{- end}}
] as const;

export type ProjectEventName = (typeof projectEventNames)[number];

export const projectEventDefinitions = {
{{- range .Events}}
  {{quote .Name}}: { schemaVersion: {{.SchemaVersion}}, scopeType: {{quote .ScopeType}}, aggregateType: {{quote .AggregateType}}, requiredPayloadFields: [{{range .RequiredPayloadFields}}{{quote .}},{{end}}] as const, terminal: {{.Terminal}} },
{{- end}}
} satisfies Record<ProjectEventName, { schemaVersion: number; scopeType: string; aggregateType: string; requiredPayloadFields: readonly string[]; terminal: boolean }>;
`))
	var goBuffer, tsBuffer bytes.Buffer
	if err := goTemplate.Execute(&goBuffer, catalog); err != nil {
		return nil, err
	}
	formattedGo, err := format.Source(goBuffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go catalog: %w", err)
	}
	if err := tsTemplate.Execute(&tsBuffer, catalog); err != nil {
		return nil, err
	}
	return map[string][]byte{
		"internal/events/generated_catalog.go":          formattedGo,
		"apps/web/src/lib/realtime/generated-events.ts": tsBuffer.Bytes(),
	}, nil
}

func discoverEventNames(root string) ([]string, error) {
	names := map[string]bool{}
	fset := token.NewFileSet()
	err := filepath.WalkDir(filepath.Join(root, "internal"), func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return err
		}
		ast.Inspect(file, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok {
				return true
			}
			callee := strings.ToLower(callName(call.Fun))
			isEventEmitter := isProjectEventEmitter(callee)
			for _, argument := range call.Args {
				literal, ok := argument.(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					continue
				}
				value, err := strconv.Unquote(literal.Value)
				if err != nil {
					continue
				}
				if isEventEmitter && eventNamePattern.MatchString(value) {
					names[value] = true
				}
				if strings.Contains(strings.ToLower(value), "insert into event_outbox") {
					for _, match := range sqlEventPattern.FindAllStringSubmatch(value, -1) {
						names[match[1]] = true
					}
				}
			}
			return true
		})
		return nil
	})
	if err != nil {
		return nil, err
	}
	result := make([]string, 0, len(names))
	for name := range names {
		result = append(result, name)
	}
	sort.Strings(result)
	return result, nil
}

type staticEventEmission struct {
	Name          string
	AggregateType string
	Location      string
}

func discoverStaticEventEmissions(root string) ([]staticEventEmission, error) {
	result := []staticEventEmission{}
	fset := token.NewFileSet()
	err := filepath.WalkDir(filepath.Join(root, "internal"), func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return err
		}
		ast.Inspect(file, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok || !isCatalogWriterCall(callName(call.Fun)) {
				return true
			}
			for index := 0; index+1 < len(call.Args); index++ {
				eventLiteral, eventOK := call.Args[index].(*ast.BasicLit)
				aggregateLiteral, aggregateOK := call.Args[index+1].(*ast.BasicLit)
				if !eventOK || !aggregateOK || eventLiteral.Kind != token.STRING || aggregateLiteral.Kind != token.STRING {
					continue
				}
				eventName, eventErr := strconv.Unquote(eventLiteral.Value)
				aggregateType, aggregateErr := strconv.Unquote(aggregateLiteral.Value)
				if eventErr != nil || aggregateErr != nil || !eventNamePattern.MatchString(eventName) || strings.Contains(aggregateType, ".") {
					continue
				}
				relative, _ := filepath.Rel(root, path)
				result = append(result, staticEventEmission{
					Name: eventName, AggregateType: aggregateType,
					Location: fmt.Sprintf("%s:%d", filepath.ToSlash(relative), fset.Position(eventLiteral.Pos()).Line),
				})
			}
			return true
		})
		return nil
	})
	return result, err
}

func discoverDirectEventOutboxWrites(root string) ([]string, error) {
	result := []string{}
	fset := token.NewFileSet()
	allowed := filepath.Clean(filepath.Join(root, "internal", "events", "catalog.go"))
	err := filepath.WalkDir(filepath.Join(root, "internal"), func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || filepath.Clean(path) == allowed {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return err
		}
		ast.Inspect(file, func(node ast.Node) bool {
			literal, ok := node.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				return true
			}
			value, err := strconv.Unquote(literal.Value)
			if err == nil && strings.Contains(strings.ToLower(value), "insert into event_outbox") {
				relative, _ := filepath.Rel(root, path)
				result = append(result, fmt.Sprintf("%s:%d", filepath.ToSlash(relative), fset.Position(literal.Pos()).Line))
			}
			return true
		})
		return nil
	})
	sort.Strings(result)
	return result, err
}

func isProjectEventEmitter(callee string) bool {
	callee = strings.ToLower(callee)
	return strings.Contains(callee, "event") &&
		(strings.Contains(callee, "insert") || strings.Contains(callee, "append") || strings.Contains(callee, "publish"))
}

func isCatalogWriterCall(callee string) bool {
	switch strings.ToLower(callee) {
	case "appendtx", "insertevent", "insertapievent":
		return true
	default:
		return false
	}
}

func callName(expression ast.Expr) string {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name
	case *ast.SelectorExpr:
		return value.Sel.Name
	default:
		return ""
	}
}

func fatalIf(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
