package authz

const (
	PermissionOrganizationRead   = "organization.read"
	PermissionOrganizationManage = "organization.manage"
	PermissionWorkspaceRead      = "workspace.read"
	PermissionWorkspaceManage    = "workspace.manage"
	PermissionProjectRead        = "project.read"
	PermissionProjectWrite       = "project.write"
	PermissionProjectDelete      = "project.delete"
	PermissionSourceRead         = "source.read"
	PermissionSourceWrite        = "source.write"
	PermissionScriptRead         = "script.read"
	PermissionScriptWrite        = "script.write"
	PermissionAssetRead          = "asset.read"
	PermissionAssetWrite         = "asset.write"
	PermissionAssetDelete        = "asset.delete"
	PermissionAssetAnalyze       = "asset.analyze"
	PermissionAssetGenerate      = "asset.generate"
	PermissionStoryboardGenerate = "storyboard.generate"
	PermissionArtifactRead       = "artifact.read"
	PermissionMediaRead          = "media.read"
	PermissionProviderRead       = "provider.read"
	PermissionProviderManage     = "provider.manage"
	PermissionPromptRead         = "prompt.read"
	PermissionPromptManage       = "prompt.manage"
	PermissionWorkflowRead       = "workflow.read"
	PermissionWorkflowRun        = "workflow.run"
	PermissionWorkflowCancel     = "workflow.cancel"
	PermissionTeamRead           = "team.read"
	PermissionTeamManage         = "team.manage"
	PermissionRoleRead           = "role.read"
	PermissionRoleManage         = "role.manage"
	PermissionAuditRead          = "audit.read"
	PermissionAdminManage        = "admin.manage"
)
