package migrationbundle

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	migrationfiles "github.com/Einzieg/cineweave/db/migrations"
)

const (
	bundleFilename   = "consolidated-up.sql"
	manifestFilename = "manifest.json"
)

var migrationNamePattern = regexp.MustCompile(`^(\d{6})_[a-z0-9_]+\.sql$`)

type Manifest struct {
	FormatVersion  int                 `json:"formatVersion"`
	HeadVersion    int64               `json:"headVersion"`
	MigrationCount int                 `json:"migrationCount"`
	BundleSHA256   string              `json:"bundleSha256"`
	Migrations     []ManifestMigration `json:"migrations"`
}

type ManifestMigration struct {
	Version int64  `json:"version"`
	Name    string `json:"name"`
	SHA256  string `json:"sha256"`
}

type migration struct {
	manifest ManifestMigration
	upSQL    string
}

func Generate(directory string) error {
	bundle, manifest, err := Build()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create migration baseline directory: %w", err)
	}
	if err := os.WriteFile(filepath.Join(directory, bundleFilename), bundle, 0o644); err != nil {
		return fmt.Errorf("write migration baseline bundle: %w", err)
	}
	if err := os.WriteFile(filepath.Join(directory, manifestFilename), manifest, 0o644); err != nil {
		return fmt.Errorf("write migration baseline manifest: %w", err)
	}
	return nil
}

func Verify(directory string) error {
	expectedBundle, expectedManifest, err := Build()
	if err != nil {
		return err
	}
	checks := []struct {
		name     string
		expected []byte
	}{
		{name: bundleFilename, expected: expectedBundle},
		{name: manifestFilename, expected: expectedManifest},
	}
	for _, check := range checks {
		path := filepath.Join(directory, check.name)
		actual, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read migration baseline %s: %w", check.name, err)
		}
		actual = normalizeNewlines(actual)
		if !bytes.Equal(actual, check.expected) {
			return fmt.Errorf("migration baseline %s is stale; run go run ./cmd/cineweave-migration-bundle generate", check.name)
		}
	}
	return nil
}

func Build() ([]byte, []byte, error) {
	migrations, err := loadMigrations(migrationfiles.FS)
	if err != nil {
		return nil, nil, err
	}
	if len(migrations) == 0 {
		return nil, nil, errors.New("no embedded migrations found")
	}

	var bundle strings.Builder
	fmt.Fprintf(&bundle, "-- CineWeave consolidated migration baseline.\n")
	fmt.Fprintf(&bundle, "-- Generated from embedded migrations 000001 through %06d.\n", migrations[len(migrations)-1].manifest.Version)
	bundle.WriteString("-- Do not edit this file and do not use it to upgrade an existing database.\n")
	bundle.WriteString("-- Existing databases must continue to use cmd/cineweave-migrate so applied hashes remain auditable.\n\n")

	manifest := Manifest{
		FormatVersion:  1,
		HeadVersion:    migrations[len(migrations)-1].manifest.Version,
		MigrationCount: len(migrations),
		Migrations:     make([]ManifestMigration, 0, len(migrations)),
	}
	for _, migration := range migrations {
		manifest.Migrations = append(manifest.Migrations, migration.manifest)
		fmt.Fprintf(&bundle, "-- migration %s sha256:%s\n", migration.manifest.Name, migration.manifest.SHA256)
		bundle.WriteString("BEGIN;\n")
		bundle.WriteString(migration.upSQL)
		bundle.WriteString("\nCOMMIT;\n\n")
	}
	bundleBytes := []byte(bundle.String())
	manifest.BundleSHA256 = hash(bundleBytes)
	manifestBytes, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, nil, fmt.Errorf("encode migration baseline manifest: %w", err)
	}
	manifestBytes = append(manifestBytes, '\n')
	return bundleBytes, manifestBytes, nil
}

func loadMigrations(source fs.FS) ([]migration, error) {
	entries, err := fs.ReadDir(source, ".")
	if err != nil {
		return nil, fmt.Errorf("read embedded migrations: %w", err)
	}
	result := make([]migration, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		matches := migrationNamePattern.FindStringSubmatch(entry.Name())
		if matches == nil {
			continue
		}
		version, err := strconv.ParseInt(matches[1], 10, 64)
		if err != nil {
			return nil, fmt.Errorf("parse migration version %s: %w", entry.Name(), err)
		}
		content, err := fs.ReadFile(source, entry.Name())
		if err != nil {
			return nil, fmt.Errorf("read migration %s: %w", entry.Name(), err)
		}
		content = normalizeNewlines(content)
		upSQL, err := extractUpSQL(entry.Name(), string(content))
		if err != nil {
			return nil, err
		}
		result = append(result, migration{
			manifest: ManifestMigration{Version: version, Name: entry.Name(), SHA256: hash(content)},
			upSQL:    upSQL,
		})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].manifest.Version < result[j].manifest.Version })
	for index, migration := range result {
		expected := int64(index + 1)
		if migration.manifest.Version != expected {
			return nil, fmt.Errorf("migration sequence has version %06d at position %06d", migration.manifest.Version, expected)
		}
	}
	return result, nil
}

func extractUpSQL(name, content string) (string, error) {
	lines := strings.Split(content, "\n")
	upIndex := -1
	downIndex := len(lines)

sections:
	for index, line := range lines {
		switch strings.TrimSpace(line) {
		case "-- +goose Up":
			if upIndex >= 0 {
				return "", fmt.Errorf("migration %s contains multiple Up sections", name)
			}
			upIndex = index
		case "-- +goose Down":
			if upIndex >= 0 {
				downIndex = index
				break sections
			}
		}
	}
	if upIndex < 0 {
		return "", fmt.Errorf("migration %s is missing an Up section", name)
	}
	filtered := make([]string, 0, downIndex-upIndex)
	for _, line := range lines[upIndex+1 : downIndex] {
		switch strings.TrimSpace(line) {
		case "-- +goose StatementBegin", "-- +goose StatementEnd":
			continue
		default:
			filtered = append(filtered, line)
		}
	}
	upSQL := strings.TrimSpace(strings.Join(filtered, "\n"))
	if upSQL == "" {
		return "", fmt.Errorf("migration %s has an empty Up section", name)
	}
	return upSQL, nil
}

func normalizeNewlines(content []byte) []byte {
	content = bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n"))
	return bytes.ReplaceAll(content, []byte("\r"), []byte("\n"))
}

func hash(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}
