package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/Einzieg/cineweave/internal/api"
	"github.com/Einzieg/cineweave/internal/projectcontrol"
)

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "verify generated contracts without writing")
	flag.Parse()

	descriptors, err := api.ProjectControlDescriptors()
	fatalIf(err)
	catalog, err := projectcontrol.BuildToolCatalog(descriptors)
	fatalIf(err)
	contracts, err := api.ProjectControlActionContracts()
	fatalIf(err)

	absRoot, err := filepath.Abs(*root)
	fatalIf(err)
	exclusions, err := loadOperationExclusions(filepath.Join(
		absRoot, "packages", "project-control", "operation-exclusions.v1.json",
	))
	fatalIf(err)
	matrix, err := projectcontrol.BuildActionMatrix(contracts, exclusions...)
	fatalIf(err)
	outputs := map[string]any{
		"packages/mcp/tool-catalog.v1.json":              catalog,
		"packages/mcp/protocol-fixtures.v1.json":         protocolFixtureDocument(),
		"packages/project-control/action-matrix.v1.json": matrix,
	}
	for relativePath, value := range outputs {
		encoded, marshalErr := json.MarshalIndent(value, "", "  ")
		fatalIf(marshalErr)
		encoded = append(encoded, '\n')
		fatalIf(writeOrCheckGenerated(absRoot, relativePath, encoded, *check))
	}
	hashSource, err := format.Source([]byte(fmt.Sprintf(`// Code generated by cmd/project-control-contracts; DO NOT EDIT.

package projectcontrol

const (
	GeneratedToolCatalogHash = %q
	GeneratedActionMatrixHash = %q
)
`, catalog.CatalogHash, matrix.MatrixHash)))
	fatalIf(err)
	fatalIf(writeOrCheckGenerated(
		absRoot,
		"internal/projectcontrol/generated_contract_hashes.go",
		hashSource,
		*check,
	))
}

func protocolFixtureDocument() map[string]any {
	metadata := map[string]any{
		"io.modelcontextprotocol/protocolVersion":    "2026-07-28",
		"io.modelcontextprotocol/clientInfo":         map[string]any{"name": "contract-fixture", "version": "1"},
		"io.modelcontextprotocol/clientCapabilities": map[string]any{},
	}
	request := func(id int, method string, params map[string]any) map[string]any {
		copy := make(map[string]any, len(params)+1)
		for key, value := range params {
			copy[key] = value
		}
		copy["_meta"] = metadata
		return map[string]any{"jsonrpc": "2.0", "id": id, "method": method, "params": copy}
	}
	return map[string]any{
		"schemaVersion":   "cineweave.mcp-protocol-fixtures.v1",
		"primaryProtocol": "2026-07-28",
		"legacyProtocols": []string{"2025-11-25", "2025-06-18"},
		"mcpFixtures": []any{
			map[string]any{
				"id": "primary-server-discover", "protocolVersion": "2026-07-28",
				"headers":  map[string]any{"Mcp-Protocol-Version": "2026-07-28", "Mcp-Method": "server/discover"},
				"request":  request(1, "server/discover", map[string]any{}),
				"expected": map[string]any{"httpStatus": 200, "resultContains": map[string]any{"supportedVersions": []string{"2026-07-28", "2025-11-25"}}},
			},
			map[string]any{
				"id": "primary-tools-list", "protocolVersion": "2026-07-28",
				"headers":  map[string]any{"Mcp-Protocol-Version": "2026-07-28", "Mcp-Method": "tools/list"},
				"request":  request(2, "tools/list", map[string]any{}),
				"expected": map[string]any{"httpStatus": 200, "resultRequired": []string{"tools"}},
			},
			map[string]any{
				"id": "primary-tools-call-success", "protocolVersion": "2026-07-28",
				"headers":  map[string]any{"Mcp-Protocol-Version": "2026-07-28", "Mcp-Method": "tools/call", "Mcp-Name": "project_get"},
				"request":  request(3, "tools/call", map[string]any{"name": "project_get", "arguments": map[string]any{"projectId": "00000000-0000-0000-0000-000000000001"}}),
				"expected": map[string]any{"httpStatus": 200, "isError": false, "structuredStatus": "succeeded"},
			},
			map[string]any{
				"id": "primary-tools-call-business-error", "protocolVersion": "2026-07-28",
				"headers":  map[string]any{"Mcp-Protocol-Version": "2026-07-28", "Mcp-Method": "tools/call", "Mcp-Name": "project_get"},
				"request":  request(4, "tools/call", map[string]any{"name": "project_get", "arguments": map[string]any{"projectId": "00000000-0000-0000-0000-000000000404"}}),
				"expected": map[string]any{"httpStatus": 200, "isError": true, "structuredErrorCode": "PROJECT_NOT_FOUND"},
			},
			map[string]any{
				"id": "primary-tools-call-permission-error", "protocolVersion": "2026-07-28",
				"headers":  map[string]any{"Mcp-Protocol-Version": "2026-07-28", "Mcp-Method": "tools/call", "Mcp-Name": "project_update"},
				"request":  request(5, "tools/call", map[string]any{"name": "project_update", "arguments": map[string]any{"projectId": "00000000-0000-0000-0000-000000000403"}}),
				"expected": map[string]any{"httpStatus": 200, "isError": true, "structuredErrorCode": "PERMISSION_DENIED"},
			},
			map[string]any{
				"id": "legacy-2025-11-25-initialize", "protocolVersion": "2025-11-25",
				"headers": map[string]any{"Mcp-Protocol-Version": "2025-11-25"},
				"request": map[string]any{
					"jsonrpc": "2.0", "id": 6, "method": "initialize",
					"params": map[string]any{
						"protocolVersion": "2025-11-25", "capabilities": map[string]any{},
						"clientInfo": map[string]any{"name": "contract-fixture", "version": "1"},
					},
				},
				"expected": map[string]any{"httpStatus": 200, "resultContains": map[string]any{"protocolVersion": "2025-11-25"}},
			},
			map[string]any{
				"id": "legacy-2025-06-18-initialize", "protocolVersion": "2025-06-18",
				"headers": map[string]any{"Mcp-Protocol-Version": "2025-06-18"},
				"request": map[string]any{
					"jsonrpc": "2.0", "id": 7, "method": "initialize",
					"params": map[string]any{
						"protocolVersion": "2025-06-18", "capabilities": map[string]any{},
						"clientInfo": map[string]any{"name": "contract-fixture", "version": "1"},
					},
				},
				"expected": map[string]any{"httpStatus": 200, "resultContains": map[string]any{"protocolVersion": "2025-06-18"}},
			},
		},
		"httpFixtures": []any{
			map[string]any{"id": "missing-authentication", "httpStatus": 401, "errorCode": "AUTHENTICATION_REQUIRED", "retryable": false, "wwwAuthenticate": "Bearer"},
			map[string]any{"id": "invalid-origin", "httpStatus": 403, "errorCode": "ORIGIN_NOT_ALLOWED", "retryable": false},
			map[string]any{"id": "request-too-large", "httpStatus": 413, "errorCode": "REQUEST_TOO_LARGE", "retryable": false},
			map[string]any{"id": "request-rate-limited", "httpStatus": 429, "errorCode": "RATE_LIMITED", "retryable": true, "retryAfterRequired": true},
			map[string]any{"id": "command-concurrency-limited", "httpStatus": 429, "errorCode": "COMMAND_CONCURRENCY_LIMIT", "retryable": true, "retryAfterRequired": true},
		},
	}
}

func writeOrCheckGenerated(root, relativePath string, content []byte, check bool) error {
	path := filepath.Join(root, filepath.FromSlash(relativePath))
	if check {
		existing, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated %s: %w", relativePath, err)
		}
		if !bytes.Equal(existing, content) {
			return fmt.Errorf("%s is stale; run go run ./cmd/project-control-contracts", relativePath)
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func loadOperationExclusions(path string) ([]projectcontrol.OperationExclusion, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var document struct {
		SchemaVersion string                              `json:"schemaVersion"`
		Exclusions    []projectcontrol.OperationExclusion `json:"exclusions"`
	}
	if err := json.Unmarshal(raw, &document); err != nil {
		return nil, fmt.Errorf("decode project control operation exclusions: %w", err)
	}
	if document.SchemaVersion != "cineweave.project-control-operation-exclusions.v1" {
		return nil, fmt.Errorf("project control operation exclusions schemaVersion is invalid")
	}
	return document.Exclusions, nil
}

func fatalIf(err error) {
	if err == nil {
		return
	}
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
