// Code generated by cmd/project-control-contracts; DO NOT EDIT.

package projectcontrol

const (
	GeneratedToolCatalogHash  = "2d732f3c231ebfdf618bc66732b6fdee806d26c7a284a789fe92fd10a7499b45"
	GeneratedActionMatrixHash = "532efd911b4ccd93703370880bc5eec789d30ad54e433f52638b8819e8612a75"
)
