// Code generated by cmd/project-control-contracts; DO NOT EDIT.

package projectcontrol

const (
	GeneratedToolCatalogHash  = "7916e42d79a957279be3637b440fd3057a8bb422715f899b36b76658f101fbe0"
	GeneratedActionMatrixHash = "532efd911b4ccd93703370880bc5eec789d30ad54e433f52638b8819e8612a75"
)
