// Code generated by cmd/project-control-contracts; DO NOT EDIT.

package projectcontrol

const (
	GeneratedToolCatalogHash  = "4770f637f958752d25458a36d050ab8e33ee5606ac93b337f65a1c29446053bb"
	GeneratedActionMatrixHash = "532efd911b4ccd93703370880bc5eec789d30ad54e433f52638b8819e8612a75"
)
