FROM temporalio/admin-tools:1.31.2@sha256:dbc5fcd6ee8f0f4d808bf765af9a87dea9d8a283abfdcfbd2fc148496ba66107 AS temporal-tools

FROM golang:1.26-alpine AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /out/temporal-schema ./cmd/temporal-schema

FROM alpine:3.21

RUN adduser -D -H cineweave
COPY --from=temporal-tools /usr/local/bin/temporal-sql-tool /usr/local/bin/temporal-sql-tool
COPY --from=temporal-tools /etc/temporal/schema /etc/temporal/schema
COPY --from=build /out/temporal-schema /temporal-schema
USER cineweave
ENTRYPOINT ["/temporal-schema"]
